"""create patients table

Revision ID: 257a513e02b8
Revises: 
Create Date: 2015-12-05 17:19:05.887156

"""

# revision identifiers, used by Alembic.
revision = '257a513e02b8'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=10), nullable=True),
    sa.Column('district', sa.Unicode(length=10), nullable=True),
    sa.Column('school', sa.Unicode(length=20), nullable=True),
    sa.Column('class_name', sa.Unicode(length=10), nullable=True),
    sa.Column('gender', sa.Unicode(length=5), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('contact_info', sa.Unicode(length=20), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('fat', sa.Unicode(length=10), nullable=True),
    sa.Column('fat_percentage', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('fat_type', sa.Unicode(length=10), nullable=True),
    sa.Column('basic_metabolism', sa.Integer(), nullable=True),
    sa.Column('measured_angle', sa.Float(), nullable=True),
    sa.Column('x_ray_num', sa.Unicode(), nullable=True),
    sa.Column('cobb_section', sa.Unicode(length=20), nullable=True),
    sa.Column('cobb_degree', sa.Float(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    ### end Alembic commands ###
